import type {StudioElement,StudioProject,V} from './types'
import {materials} from './library'
const CH='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_$'
function hash32(s:string,seed=2166136261){let h=seed>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
export function guidFor(key:string){let o='',a=hash32(key),b=hash32(key,0x9e3779b9),c=hash32(key,0x85ebca6b);for(let i=0;i<22;i++){const v=(a^((b<<((i%5)+1))>>>0)^c^i)>>>0;o+=CH[v%64];a=(Math.imul(a,1664525)+1013904223)>>>0;b=(Math.imul(b,1103515245)+12345)>>>0;c=(c^c<<13^c>>>17^c<<5)>>>0}return o}
const esc=(s:unknown)=>String(s??'').replace(/'/g,"''"),f=(n:number)=>Number.isFinite(n)?Number(n.toFixed(6)).toString():'0'
const ifcVal=(v:V)=>typeof v==='number'?`IFCREAL(${f(v)})`:typeof v==='boolean'?`IFCBOOLEAN(${v?'.T.':'.F.'})`:`IFCLABEL('${esc(v)}')`
class W{n=1;lines:string[]=[];add(x:string){const i=this.n++;this.lines.push(`#${i}=${x};`);return i}}
function pt(w:W,x:number,y:number,z:number){return w.add(`IFCCARTESIANPOINT((${f(x)},${f(y)},${f(z)}))`)}
function di(w:W,x:number,y:number,z:number){return w.add(`IFCDIRECTION((${f(x)},${f(y)},${f(z)}))`)}
function plc(w:W,x:number,y:number,z:number){const p=pt(w,x,y,z),a=di(w,0,0,1),r=di(w,1,0,0),ax=w.add(`IFCAXIS2PLACEMENT3D(#${p},#${a},#${r})`);return w.add(`IFCLOCALPLACEMENT($,#${ax})`)}
function shp(w:W,x:number,y:number,z:number){const p=pt(w,0,0,0),a=di(w,0,0,1),r=di(w,1,0,0),ax=w.add(`IFCAXIS2PLACEMENT3D(#${p},#${a},#${r})`),pr=w.add(`IFCRECTANGLEPROFILEDEF(.AREA.,$,#${ax},${f(Math.max(.02,x))},${f(Math.max(.02,y))})`),d=di(w,0,0,1),so=w.add(`IFCEXTRUDEDAREASOLID(#${pr},#${ax},#${d},${f(Math.max(.02,z))})`),rep=w.add(`IFCSHAPEREPRESENTATION($,'Body','SweptSolid',(#${so}))`);return w.add(`IFCPRODUCTDEFINITIONSHAPE($,$,(#${rep}))`)}
function pset(w:W,owner:number,g:string,name:string,props:Record<string,V>){const ps=Object.entries(props).filter(([,v])=>v!==undefined).map(([k,v])=>w.add(`IFCPROPERTYSINGLEVALUE('${esc(k)}',$,${ifcVal(v)},$)`));if(!ps.length)return;const p=w.add(`IFCPROPERTYSET('${guidFor(g+name)}',$,'${esc(name)}',$,(${ps.map(i=>`#${i}`).join(',')}))`);w.add(`IFCRELDEFINESBYPROPERTIES('${guidFor(g+name+'rel')}',$,$,$,(#${owner}),#${p})`)}
function cls(e:StudioElement){const t=e.type.toLowerCase();if(t.includes('column')||t==='pillar')return'IFCCOLUMN';if(t.includes('beam'))return'IFCBEAM';if(t.includes('slab'))return'IFCSLAB';if(t.includes('wall'))return'IFCWALL';if(t.includes('footing')||t.includes('foundation'))return'IFCFOOTING';if(t.includes('door'))return'IFCDOOR';if(t.includes('window'))return'IFCWINDOW';if(t.includes('stair'))return'IFCSTAIR';if(t.includes('roof'))return'IFCROOF';return'IFCBUILDINGELEMENTPROXY'}
export function projectToIfc(p:StudioProject){const w=new W(),pg=guidFor(`RJP3D:${p.id}`),org=w.add(`IFCORGANIZATION($,'RJP Engineering',$,$,$)`),person=w.add(`IFCPERSON($,$,'RJP',$,$,$,$,$,$)`),pa=w.add(`IFCPERSONANDORGANIZATION(#${person},#${org},$)`),app=w.add(`IFCAPPLICATION(#${org},'1.1.0','RJP 3D Studio','RJP_3D_STUDIO')`),hist=w.add(`IFCOWNERHISTORY(#${pa},#${app},$,.ADDED.,$,$,$,0)`),pr=w.add(`IFCPROJECT('${pg}',#${hist},'${esc(p.name)}',$,$,$,$,$,$)`),spl=plc(w,0,0,0),site=w.add(`IFCSITE('${guidFor(pg+'site')}',#${hist},'Site',$,$,#${spl},$,$,.ELEMENT.,$,$,$,$,$)`),bpl=plc(w,0,0,0),bld=w.add(`IFCBUILDING('${guidFor(pg+'building')}',#${hist},'${esc(p.name)}',$,$,#${bpl},$,$,.ELEMENT.,$,$,$)`);w.add(`IFCRELAGGREGATES('${guidFor(pg+'r1')}',#${hist},$,$,#${pr},(#${site}))`);w.add(`IFCRELAGGREGATES('${guidFor(pg+'r2')}',#${hist},$,$,#${site},(#${bld}))`);const ids:number[]=[]
 for(const e of p.elements){const g=String(e.properties.ifcGuid||guidFor(`${pg}:${e.id}`));const pl=plc(w,e.position.x,e.position.y,e.position.z),sh=shp(w,e.size.x,e.size.y,e.size.z),c=cls(e);let body=`${c}('${g}',#${hist},'${esc(e.name)}',$,$,#${pl},#${sh},$`;if(c==='IFCFOOTING')body+=`,.PAD_FOOTING.)`;else if(c==='IFCSLAB')body+=`,.FLOOR.)`;else if(c==='IFCDOOR'||c==='IFCWINDOW')body+=`,$,$,$,$,$)`;else if(c==='IFCROOF')body+=`,.NOTDEFINED.)`;else if(c==='IFCSTAIR')body+=`,.NOTDEFINED.)`;else if(c==='IFCBUILDINGELEMENTPROXY')body+=`,.NOTDEFINED.)`;else body+=`,$)`;const id=w.add(body);ids.push(id);pset(w,id,g,'Pset_RJP_Identity',{RJP_Id:e.id,RJP_Type:e.type,RJP_Category:e.category,RJP_Source:e.source,RJP_Level:e.level??null});pset(w,id,g,'Pset_RJP_Geometry',{RJP_X:e.position.x,RJP_Y:e.position.y,RJP_Z:e.position.z,RJP_RotX:e.rotation.x,RJP_RotY:e.rotation.y,RJP_RotationZ:e.rotation.z,RJP_SizeX:e.size.x,RJP_SizeY:e.size.y,RJP_SizeZ:e.size.z});pset(w,id,g,'Pset_RJP_Material',{RJP_MaterialId:e.material.id,RJP_Material:e.material.name,RJP_Family:e.material.family,...e.material.properties});if(e.results)pset(w,id,g,'Pset_RJP_Engineering',e.results);e.properties.ifcGuid=g}
 if(ids.length)w.add(`IFCRELCONTAINEDINSPATIALSTRUCTURE('${guidFor(pg+'contains')}',#${hist},$,$,(${ids.map(i=>`#${i}`).join(',')}),#${bld})`);pset(w,pr,pg,'Pset_RJP_Project',{RJP_App:'RJP 3D Studio',RJP_Version:'1.1.0',RJP_ProjectId:p.id,RJP_ProjectName:p.name,RJP_Location:p.location,RJP_Solution:p.solution});return`ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('ViewDefinition [CoordinationView_V2.0]'),'2;1');\nFILE_NAME('${esc(p.name)}.ifc','${new Date().toISOString()}',('RJP'),('RJP Engineering'),'RJP 3D Studio 1.1.0','RJP 3D Studio','');\nFILE_SCHEMA(('IFC4'));\nENDSEC;\nDATA;\n${w.lines.join('\n')}\nENDSEC;\nEND-ISO-10303-21;\n`}
export function downloadIfc(p:StudioProject){const u=URL.createObjectURL(new Blob([projectToIfc(p)],{type:'application/x-step'})),a=document.createElement('a');a.href=u;a.download=`${p.name.replace(/[^a-z0-9_-]+/gi,'_')||'RJP_3D'}_Modelo.ifc`;a.click();URL.revokeObjectURL(u)}

const entityRe=/#(\d+)=(IFCBEAM|IFCCOLUMN|IFCSLAB|IFCWALL|IFCFOOTING|IFCDOOR|IFCWINDOW|IFCROOF|IFCSTAIR|IFCBUILDINGELEMENTPROXY)\('([^']*)',[^,]*,'([^']*)'/gi
function propertyMap(text:string){const values=new Map<number,{name:string;value:V}>();for(const m of text.matchAll(/#(\d+)=IFCPROPERTYSINGLEVALUE\('([^']*)'[^;]*?(?:IFCLABEL\('([^']*)'\)|IFCREAL\(([-+0-9.eE]+)\)|IFCINTEGER\(([-+0-9]+)\)|IFCBOOLEAN\((\.T\.|\.F\.)\))/gi)){let v:V=m[3]??m[4]??m[5]??m[6]??null;if(m[4]!==undefined||m[5]!==undefined)v=Number(v);if(m[6]!==undefined)v=m[6]==='.T.';values.set(Number(m[1]),{name:m[2],value:v})}const psets=new Map<number,Record<string,V>>();for(const m of text.matchAll(/#(\d+)=IFCPROPERTYSET\('[^']*'[^;]*?\(([^)]*)\)\)/gi)){const props:Record<string,V>={};for(const id of m[2].match(/#\d+/g)||[]){const p=values.get(Number(id.slice(1)));if(p)props[p.name]=p.value}psets.set(Number(m[1]),props)}const owners=new Map<number,Record<string,V>>();for(const m of text.matchAll(/IFCRELDEFINESBYPROPERTIES\('[^']*'[^;]*?\((#[0-9]+(?:,#[0-9]+)*)\),#(\d+)\)/gi)){const props=psets.get(Number(m[2]));if(!props)continue;for(const id of m[1].match(/#\d+/g)||[])owners.set(Number(id.slice(1)),{...(owners.get(Number(id.slice(1)))||{}),...props})}return owners}
function typeFromIfc(c:string){return c==='IFCCOLUMN'?'column':c==='IFCBEAM'?'beam':c==='IFCSLAB'?'slab':c==='IFCWALL'?'wall':c==='IFCFOOTING'?'footing':c==='IFCDOOR'?'door':c==='IFCWINDOW'?'window':c==='IFCROOF'?'roof':c==='IFCSTAIR'?'stair':'object'}
export function projectFromIfc(text:string,current?:StudioProject){if(!/FILE_SCHEMA\s*\(\('IFC/i.test(text)&&!/ISO-10303-21/i.test(text))throw new Error('O ficheiro não parece ser IFC STEP.');const props=propertyMap(text),els:StudioElement[]=[];for(const m of text.matchAll(entityRe)){const idn=Number(m[1]),c=m[2].toUpperCase(),guid=m[3],name=m[4]||`${c} ${guid}`,p=props.get(idn)||{},type=String(p.RJP_Type||typeFromIfc(c));els.push({id:String(p.RJP_Id||guid),name,type,category:String(p.RJP_Category||'IFC / BIM'),level:p.RJP_Level?String(p.RJP_Level):undefined,position:{x:Number(p.RJP_X||0),y:Number(p.RJP_Y||0),z:Number(p.RJP_Z||0)},rotation:{x:Number(p.RJP_RotX||0),y:Number(p.RJP_RotY||0),z:Number(p.RJP_RotationZ||0)},size:{x:Number(p.RJP_SizeX||1),y:Number(p.RJP_SizeY||.3),z:Number(p.RJP_SizeZ||1)},material:{id:String(p.RJP_MaterialId||'ifc-material'),name:String(p.RJP_Material||'Material IFC'),family:String(p.RJP_Family||'IFC'),properties:{}},source:String(p.RJP_Source||'IFC/openBIM'),properties:{...p,ifcGuid:guid},results:{}})}if(!els.length)throw new Error('IFC válido, mas não foram encontradas entidades suportadas nesta versão.');const pn=(text.match(/IFCPROPERTYSINGLEVALUE\('RJP_ProjectName'[^;]*IFCLABEL\('([^']*)'/i)||[])[1],loc=(text.match(/IFCPROPERTYSINGLEVALUE\('RJP_Location'[^;]*IFCLABEL\('([^']*)'/i)||[])[1],sol=(text.match(/IFCPROPERTYSINGLEVALUE\('RJP_Solution'[^;]*IFCLABEL\('([^']*)'/i)||[])[1] as StudioProject['solution']|undefined;const now=new Date().toISOString();return{id:current?.id||`IFC-${Date.now()}`,name:pn||current?.name||'Projeto IFC',location:loc||current?.location||'',solution:sol&&['traditional','lsf','timber'].includes(sol)?sol:(current?.solution||'traditional'),elements:els,createdAt:current?.createdAt||now,updatedAt:now}}
export function mergeIfc(current:StudioProject,incoming:StudioProject){const byGuid=new Map(current.elements.map(e=>[String(e.properties.ifcGuid||''),e]));const byId=new Map(current.elements.map(e=>[e.id,e]));const touched=new Set<string>();const incomingMerged=incoming.elements.map(e=>{const g=String(e.properties.ifcGuid||''),old=(g&&byGuid.get(g))||byId.get(e.id);if(!old)return e;touched.add(old.id);return{...old,...e,id:old.id,properties:{...old.properties,...e.properties},material:e.material.name==='Material IFC'?old.material:e.material}});return{...current,name:incoming.name||current.name,location:incoming.location||current.location,elements:[...current.elements.filter(e=>!touched.has(e.id)&&!incoming.elements.some(i=>String(i.properties.ifcGuid||'')===String(e.properties.ifcGuid||''))),...incomingMerged],updatedAt:new Date().toISOString()}}
