import React,{useEffect,useRef} from 'react'
import * as THREE from 'three'
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'
import {TransformControls} from 'three/examples/jsm/controls/TransformControls.js'
import type {SourceDrawing,StudioElement} from './types'
export type EditMode='translate'|'rotate'|'scale'
const textureColor=(t?:string)=>({concrete:0xb8c0c8,steel:0x8a9aa8,wood:0xa47747,galvanized:0xb7c4cf,brick:0xb15c43,block:0x9ca3a8,glass:0x76c5e8,tile:0xb65a42,sandwich:0x8da3b3,plaster:0xe7e1d5,ceramic:0xe8e8e8,insulation:0xe9d87a,stone:0x8d8173,gypsum:0xe7e4dc,pvc:0xd8d8d8,aluminium:0xaeb9c2,soil:0x6b5b43}[t||'']||0x7aa8d6)
export default function ThreeViewport({elements,selectedId,onSelect,onChange,mode='translate',viewMode='3d',cadOverlay,cadScale=1,onCanvasPoint}:{elements:StudioElement[];selectedId:string|null;onSelect:(id:string|null)=>void;onChange:(id:string,p:Partial<StudioElement>)=>void;mode?:EditMode;viewMode?:'3d'|'top'|'front'|'right';cadOverlay?:SourceDrawing;cadScale?:number;onCanvasPoint?:(p:{x:number;y:number})=>void}){const host=useRef<HTMLDivElement>(null)
 useEffect(()=>{const el=host.current;if(!el)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x071a2e);const camera=new THREE.PerspectiveCamera(48,1,.05,1000);camera.up.set(0,0,1);if(viewMode==='top')camera.position.set(5,5,35);else if(viewMode==='front')camera.position.set(5,-35,4);else if(viewMode==='right')camera.position.set(35,5,4);else camera.position.set(12,-16,11);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;el.innerHTML='';el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x223344,2.2));const dl=new THREE.DirectionalLight(0xffffff,2.6);dl.position.set(8,-8,15);dl.castShadow=true;scene.add(dl);const grid=new THREE.GridHelper(60,60,0x33506d,0x17314b);grid.rotation.x=Math.PI/2;scene.add(grid);
 if(cadOverlay?.cadSegments?.length&&cadOverlay.cadBounds){const b=cadOverlay.cadBounds;const verts:number[]=[];for(const s of cadOverlay.cadSegments){const l=cadOverlay.layers?.find(x=>x.name===s.layer);if(l&&l.visible===false)continue;verts.push((s.x1-b.minX)*cadScale,(s.y1-b.minY)*cadScale,.015,(s.x2-b.minX)*cadScale,(s.y2-b.minY)*cadScale,.015)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));const m=new THREE.LineBasicMaterial({color:0x42e6d7,transparent:true,opacity:.48});const lines=new THREE.LineSegments(g,m);scene.add(lines)}
 const group=new THREE.Group();scene.add(group);const objMap=new Map<string,THREE.Mesh>();for(const e of elements){const geo=new THREE.BoxGeometry(Math.max(.03,e.size.x),Math.max(.03,e.size.y),Math.max(.03,e.size.z));const phase=String(e.properties.phase||'Novo');const hosted=Boolean(e.properties.hostWallId);const mat=new THREE.MeshStandardMaterial({color:phase==='Demolir'?0xcf6b6b:phase==='Existente'?0xa3acb5:textureColor(e.material.texture),roughness:.62,metalness:e.material.family.includes('Aço') ? 0.35 : 0.05,transparent:e.type==='window'||e.type==='pool'||phase==='Existente',opacity:e.type==='window'||e.type==='pool'?0.55:phase==='Existente'?.72:1,emissive:hosted?0x123b36:0x000000,emissiveIntensity:hosted?.35:0});const mesh=new THREE.Mesh(geo,mat);mesh.position.set(e.position.x,e.position.y,e.position.z);mesh.rotation.set(e.rotation.x,e.rotation.y,e.rotation.z);mesh.userData.id=e.id;mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);objMap.set(e.id,mesh)}
 const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(3,0,2.5);orbit.screenSpacePanning=true;if(viewMode!=='3d'){orbit.enableRotate=false;orbit.target.set(5,5,viewMode==='top'?0:3);camera.lookAt(orbit.target)}const tc=new TransformControls(camera,renderer.domElement);tc.setMode(mode);tc.setTranslationSnap(.05);tc.setRotationSnap(THREE.MathUtils.degToRad(5));tc.setScaleSnap(.05);scene.add(tc.getHelper());const selected=selectedId?objMap.get(selectedId):undefined;if(selected)tc.attach(selected);tc.addEventListener('dragging-changed',(ev:any)=>orbit.enabled=!ev.value);tc.addEventListener('mouseUp',()=>{const o=tc.object as THREE.Mesh|undefined;if(!o)return;onChange(String(o.userData.id),{position:{x:+o.position.x.toFixed(4),y:+o.position.y.toFixed(4),z:+o.position.z.toFixed(4)},rotation:{x:o.rotation.x,y:o.rotation.y,z:o.rotation.z},size:{x:Math.max(.02,Math.abs(o.scale.x)*((elements.find(e=>e.id===o.userData.id)?.size.x)||1)),y:Math.max(.02,Math.abs(o.scale.y)*((elements.find(e=>e.id===o.userData.id)?.size.y)||1)),z:Math.max(.02,Math.abs(o.scale.z)*((elements.find(e=>e.id===o.userData.id)?.size.z)||1))}})});const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),0);const click=(ev:MouseEvent)=>{if((tc as any).dragging)return;const r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);if(onCanvasPoint&&viewMode==='top'){const p=new THREE.Vector3();if(ray.ray.intersectPlane(plane,p)){onCanvasPoint({x:p.x,y:p.y});return}}const hit=ray.intersectObjects(Array.from(objMap.values()),false)[0];onSelect(hit?String(hit.object.userData.id):null)};renderer.domElement.addEventListener('pointerdown',click);const resize=()=>{const w=el.clientWidth,h=Math.max(460,el.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();const ro=new ResizeObserver(resize);ro.observe(el);let af=0;const loop=()=>{orbit.update();renderer.render(scene,camera);af=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(af);ro.disconnect();renderer.domElement.removeEventListener('pointerdown',click);orbit.dispose();tc.dispose();renderer.dispose();el.innerHTML=''}},[elements,selectedId,mode,viewMode,cadOverlay,cadScale,onCanvasPoint])
 return <div className="three-host" ref={host}/>
}
